import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    //O front-end.
    <>
      <Head>
        <title>iShop Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charset="UTF-8"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <body>
          <main >
            <p>Oi.</p>
          </main>
        </body>
        <footer>

        </footer>
      </div>
    </>
  );
}
