// pages/index.js

import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';

export default function Home() {
  const [produtos, setProdutos] = useState([]);

  useEffect(() => {
    async function fetchProdutos() {
      try {
        const response = await fetch('/api/produto?loja=MinhaLoja');
        const data = await response.json();
        setProdutos(data);
      } catch (error) {
        console.error("Erro ao carregar produtos:", error);
      }
    }

    fetchProdutos();
  }, []);

  return (
    <>
      <Head>
        <title>iShop Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <nav id="navbar" className="navbar bg-primary col-12 navbar-expand-lg position-fixed">
            <div className="container-fluid col-11 m-auto">
              <Link href="/home">
                <Image
                  src="/Varios-12-150ppp-01.jpg"
                  alt="LOGO"
                  width={40}
                  height={40}
                  className="cursor-pointer"
                />
              </Link>
              <button
                className="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span className="navbar-toggler-icon"></span>
              </button>
              <div className="collapse navbar-collapse" id="navbarNav">
                <ul className="navbar-nav ms-auto">
                  <li className="nav-item">
                    <Link href="/home" className="nav-link text-light">Home</Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/funcionario" className="nav-link text-light">Funcionário</Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/cliente" className="nav-link text-light">Cliente</Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/armazem" className="nav-link text-light">Armazém</Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/promocao" className="nav-link text-light">Promoção</Link>
                  </li>
                  <li className="nav-item">
                    <Link href="#top" className="nav-link text-light">Produto</Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/loja_parceira" className="nav-link text-light">Parceiro</Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/index" className="nav-link text-light">Logout</Link>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </section>

        <section id="top" className="d-flex flex-column min-vh-100">
          <div className="container row m-auto">
            <Image src="/43160.jpg" alt="Uma loja rodeada por icones." className="col-sm-6 col-6 img-fluid" style={{ marginTop: "100px", width: "350px", height: "350px" }} />
            <div className="container d-flex align-items-center col-6" style={{ marginTop: "100px", textAlign: "justify" }}>
              Bem-vindo ao iShop Manager! Gerencie seus produtos e estoque de forma eficiente e segura.
            </div>
          </div>
        </section>

        <section id="Cards" className="container d-flex justify-content-center mt-5 mb-5">
          {produtos.map(produto => (
            <div className="card" style={{ width: "18rem" }} key={produto.objectId}>
              <Image src="/product-image.jpg" alt={produto.nome} className="card-img-top" width={250} height={220} />
              <div className="card-body">
                <h5 className="card-title">{produto.nome}</h5>
                <p className="card-text">{produto.categoria} - R${produto.preco}</p>
              </div>
            </div>
          ))}
        </section>

        <footer className="d-flex align-items-center justify-content-center py-3 mt-4">
          <p className="mb-0">
            &copy; {new Date().getFullYear()} iShop Manager. Todos os direitos reservados.
          </p>
        </footer>
      </main>
    </>
  );
}
